workflows:
  android-build:
    name: Android APK Build
    instance_type: mac_mini_intel
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Selecionar Java 17
        script: |
          jdk-switch --version 17
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
      
